/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Escrow {
  export type EscrowDataStruct = {
    jobId: BytesLike;
    buyer: AddressLike;
    provider: AddressLike;
    amount: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    timeoutAt: BigNumberish;
  };

  export type EscrowDataStructOutput = [
    jobId: string,
    buyer: string,
    provider: string,
    amount: bigint,
    status: bigint,
    createdAt: bigint,
    timeoutAt: bigint
  ] & {
    jobId: string;
    buyer: string;
    provider: string;
    amount: bigint;
    status: bigint;
    createdAt: bigint;
    timeoutAt: bigint;
  };
}

export declare namespace JobRegistry {
  export type JobStruct = {
    id: BytesLike;
    buyer: AddressLike;
    provider: AddressLike;
    amount: BigNumberish;
    status: BigNumberish;
    tracked: boolean;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
    reasoningHash: string;
  };

  export type JobStructOutput = [
    id: string,
    buyer: string,
    provider: string,
    amount: bigint,
    status: bigint,
    tracked: boolean,
    createdAt: bigint,
    completedAt: bigint,
    reasoningHash: string
  ] & {
    id: string;
    buyer: string;
    provider: string;
    amount: bigint;
    status: bigint;
    tracked: boolean;
    createdAt: bigint;
    completedAt: bigint;
    reasoningHash: string;
  };
}

export declare namespace ProviderRegistry {
  export type ProviderStruct = {
    owner: AddressLike;
    metadataURI: string;
    isActive: boolean;
    registeredAt: BigNumberish;
    hourlyRate: BigNumberish;
  };

  export type ProviderStructOutput = [
    owner: string,
    metadataURI: string,
    isActive: boolean,
    registeredAt: bigint,
    hourlyRate: bigint
  ] & {
    owner: string;
    metadataURI: string;
    isActive: boolean;
    registeredAt: bigint;
    hourlyRate: bigint;
  };
}

export interface ComputeRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "USER_ROLE"
      | "VIEWER_ROLE"
      | "acceptJob"
      | "addViewer"
      | "adminRefund"
      | "completeJob"
      | "createJob"
      | "escrow"
      | "failJob"
      | "getBuyerJobs"
      | "getEscrow"
      | "getJob"
      | "getProvider"
      | "getProviderJobs"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isActiveProvider"
      | "isRegisteredProvider"
      | "jobRegistry"
      | "providerRegistry"
      | "registerProvider"
      | "removeViewer"
      | "renounceRole"
      | "requestRefund"
      | "revokeRole"
      | "supportsInterface"
      | "updateProvider"
      | "updateProviderStatus"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComputeJobCompleted"
      | "ComputeJobCreated"
      | "ProviderRegisteredViaRouter"
      | "ProviderStatusUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USER_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "VIEWER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptJob",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addViewer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeJob",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [AddressLike, BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "failJob",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyerJobs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getJob", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderJobs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jobRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerProvider",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeViewer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProvider",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProviderStatus",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USER_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VIEWER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "acceptJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addViewer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "failJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBuyerJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isActiveProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jobRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeViewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProviderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace ComputeJobCompletedEvent {
  export type InputTuple = [jobId: BytesLike, completedAt: BigNumberish];
  export type OutputTuple = [jobId: string, completedAt: bigint];
  export interface OutputObject {
    jobId: string;
    completedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComputeJobCreatedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    buyer: AddressLike,
    provider: AddressLike,
    amount: BigNumberish,
    tracked: boolean
  ];
  export type OutputTuple = [
    jobId: string,
    buyer: string,
    provider: string,
    amount: bigint,
    tracked: boolean
  ];
  export interface OutputObject {
    jobId: string;
    buyer: string;
    provider: string;
    amount: bigint;
    tracked: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderRegisteredViaRouterEvent {
  export type InputTuple = [
    provider: AddressLike,
    metadataURI: string,
    hourlyRate: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    metadataURI: string,
    hourlyRate: bigint
  ];
  export interface OutputObject {
    provider: string;
    metadataURI: string;
    hourlyRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderStatusUpdatedEvent {
  export type InputTuple = [provider: AddressLike, isActive: boolean];
  export type OutputTuple = [provider: string, isActive: boolean];
  export interface OutputObject {
    provider: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComputeRouter extends BaseContract {
  connect(runner?: ContractRunner | null): ComputeRouter;
  waitForDeployment(): Promise<this>;

  interface: ComputeRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  USER_ROLE: TypedContractMethod<[], [string], "view">;

  VIEWER_ROLE: TypedContractMethod<[], [string], "view">;

  acceptJob: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  addViewer: TypedContractMethod<[account: AddressLike], [void], "nonpayable">;

  adminRefund: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  completeJob: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  createJob: TypedContractMethod<
    [
      provider: AddressLike,
      amount: BigNumberish,
      tracked: boolean,
      reasoningHash: string
    ],
    [string],
    "nonpayable"
  >;

  escrow: TypedContractMethod<[], [string], "view">;

  failJob: TypedContractMethod<
    [jobId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getBuyerJobs: TypedContractMethod<[buyer: AddressLike], [string[]], "view">;

  getEscrow: TypedContractMethod<
    [jobId: BytesLike],
    [Escrow.EscrowDataStructOutput],
    "view"
  >;

  getJob: TypedContractMethod<
    [jobId: BytesLike],
    [JobRegistry.JobStructOutput],
    "view"
  >;

  getProvider: TypedContractMethod<
    [owner: AddressLike],
    [ProviderRegistry.ProviderStructOutput],
    "view"
  >;

  getProviderJobs: TypedContractMethod<
    [provider: AddressLike],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isActiveProvider: TypedContractMethod<
    [provider: AddressLike],
    [boolean],
    "view"
  >;

  isRegisteredProvider: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  jobRegistry: TypedContractMethod<[], [string], "view">;

  providerRegistry: TypedContractMethod<[], [string], "view">;

  registerProvider: TypedContractMethod<
    [metadataURI: string, hourlyRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeViewer: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestRefund: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateProvider: TypedContractMethod<
    [metadataURI: string, hourlyRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateProviderStatus: TypedContractMethod<
    [isActive: boolean],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VIEWER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptJob"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addViewer"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminRefund"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeJob"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      provider: AddressLike,
      amount: BigNumberish,
      tracked: boolean,
      reasoningHash: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "failJob"
  ): TypedContractMethod<
    [jobId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBuyerJobs"
  ): TypedContractMethod<[buyer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [Escrow.EscrowDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [JobRegistry.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProvider"
  ): TypedContractMethod<
    [owner: AddressLike],
    [ProviderRegistry.ProviderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProviderJobs"
  ): TypedContractMethod<[provider: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActiveProvider"
  ): TypedContractMethod<[provider: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegisteredProvider"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "jobRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "providerRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerProvider"
  ): TypedContractMethod<
    [metadataURI: string, hourlyRate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeViewer"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestRefund"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateProvider"
  ): TypedContractMethod<
    [metadataURI: string, hourlyRate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProviderStatus"
  ): TypedContractMethod<[isActive: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ComputeJobCompleted"
  ): TypedContractEvent<
    ComputeJobCompletedEvent.InputTuple,
    ComputeJobCompletedEvent.OutputTuple,
    ComputeJobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ComputeJobCreated"
  ): TypedContractEvent<
    ComputeJobCreatedEvent.InputTuple,
    ComputeJobCreatedEvent.OutputTuple,
    ComputeJobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderRegisteredViaRouter"
  ): TypedContractEvent<
    ProviderRegisteredViaRouterEvent.InputTuple,
    ProviderRegisteredViaRouterEvent.OutputTuple,
    ProviderRegisteredViaRouterEvent.OutputObject
  >;
  getEvent(
    key: "ProviderStatusUpdated"
  ): TypedContractEvent<
    ProviderStatusUpdatedEvent.InputTuple,
    ProviderStatusUpdatedEvent.OutputTuple,
    ProviderStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "ComputeJobCompleted(bytes32,uint256)": TypedContractEvent<
      ComputeJobCompletedEvent.InputTuple,
      ComputeJobCompletedEvent.OutputTuple,
      ComputeJobCompletedEvent.OutputObject
    >;
    ComputeJobCompleted: TypedContractEvent<
      ComputeJobCompletedEvent.InputTuple,
      ComputeJobCompletedEvent.OutputTuple,
      ComputeJobCompletedEvent.OutputObject
    >;

    "ComputeJobCreated(bytes32,address,address,uint256,bool)": TypedContractEvent<
      ComputeJobCreatedEvent.InputTuple,
      ComputeJobCreatedEvent.OutputTuple,
      ComputeJobCreatedEvent.OutputObject
    >;
    ComputeJobCreated: TypedContractEvent<
      ComputeJobCreatedEvent.InputTuple,
      ComputeJobCreatedEvent.OutputTuple,
      ComputeJobCreatedEvent.OutputObject
    >;

    "ProviderRegisteredViaRouter(address,string,uint256)": TypedContractEvent<
      ProviderRegisteredViaRouterEvent.InputTuple,
      ProviderRegisteredViaRouterEvent.OutputTuple,
      ProviderRegisteredViaRouterEvent.OutputObject
    >;
    ProviderRegisteredViaRouter: TypedContractEvent<
      ProviderRegisteredViaRouterEvent.InputTuple,
      ProviderRegisteredViaRouterEvent.OutputTuple,
      ProviderRegisteredViaRouterEvent.OutputObject
    >;

    "ProviderStatusUpdated(address,bool)": TypedContractEvent<
      ProviderStatusUpdatedEvent.InputTuple,
      ProviderStatusUpdatedEvent.OutputTuple,
      ProviderStatusUpdatedEvent.OutputObject
    >;
    ProviderStatusUpdated: TypedContractEvent<
      ProviderStatusUpdatedEvent.InputTuple,
      ProviderStatusUpdatedEvent.OutputTuple,
      ProviderStatusUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
