/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Escrow {
  export type EscrowDataStruct = {
    jobId: BytesLike;
    buyer: AddressLike;
    provider: AddressLike;
    amount: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    timeoutAt: BigNumberish;
  };

  export type EscrowDataStructOutput = [
    jobId: string,
    buyer: string,
    provider: string,
    amount: bigint,
    status: bigint,
    createdAt: bigint,
    timeoutAt: bigint
  ] & {
    jobId: string;
    buyer: string;
    provider: string;
    amount: bigint;
    status: bigint;
    createdAt: bigint;
    timeoutAt: bigint;
  };
}

export interface EscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "REFUND_TIMEOUT"
      | "emergencyWithdraw"
      | "escrows"
      | "getContractBalance"
      | "getEscrow"
      | "isRefundAvailable"
      | "jobRegistry"
      | "lockFunds"
      | "owner"
      | "refund"
      | "releaseFunds"
      | "renounceOwnership"
      | "setJobRegistry"
      | "transferOwnership"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsLocked"
      | "FundsRefunded"
      | "FundsReleased"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "REFUND_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRefundAvailable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jobRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockFunds",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setJobRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "REFUND_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRefundAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jobRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockFunds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setJobRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace FundsLockedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    buyer: AddressLike,
    provider: AddressLike,
    amount: BigNumberish,
    timeoutAt: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    buyer: string,
    provider: string,
    amount: bigint,
    timeoutAt: bigint
  ];
  export interface OutputObject {
    jobId: string;
    buyer: string;
    provider: string;
    amount: bigint;
    timeoutAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsRefundedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    buyer: AddressLike,
    amount: BigNumberish,
    refundedAt: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    buyer: string,
    amount: bigint,
    refundedAt: bigint
  ];
  export interface OutputObject {
    jobId: string;
    buyer: string;
    amount: bigint;
    refundedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    provider: AddressLike,
    amount: BigNumberish,
    releasedAt: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    provider: string,
    amount: bigint,
    releasedAt: bigint
  ];
  export interface OutputObject {
    jobId: string;
    provider: string;
    amount: bigint;
    releasedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Escrow extends BaseContract {
  connect(runner?: ContractRunner | null): Escrow;
  waitForDeployment(): Promise<this>;

  interface: EscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  REFUND_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint] & {
        jobId: string;
        buyer: string;
        provider: string;
        amount: bigint;
        status: bigint;
        createdAt: bigint;
        timeoutAt: bigint;
      }
    ],
    "view"
  >;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getEscrow: TypedContractMethod<
    [jobId: BytesLike],
    [Escrow.EscrowDataStructOutput],
    "view"
  >;

  isRefundAvailable: TypedContractMethod<[jobId: BytesLike], [boolean], "view">;

  jobRegistry: TypedContractMethod<[], [string], "view">;

  lockFunds: TypedContractMethod<
    [jobId: BytesLike, provider: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  releaseFunds: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setJobRegistry: TypedContractMethod<
    [_jobRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "REFUND_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint] & {
        jobId: string;
        buyer: string;
        provider: string;
        amount: bigint;
        status: bigint;
        createdAt: bigint;
        timeoutAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [Escrow.EscrowDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRefundAvailable"
  ): TypedContractMethod<[jobId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "jobRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lockFunds"
  ): TypedContractMethod<
    [jobId: BytesLike, provider: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setJobRegistry"
  ): TypedContractMethod<[_jobRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FundsLocked"
  ): TypedContractEvent<
    FundsLockedEvent.InputTuple,
    FundsLockedEvent.OutputTuple,
    FundsLockedEvent.OutputObject
  >;
  getEvent(
    key: "FundsRefunded"
  ): TypedContractEvent<
    FundsRefundedEvent.InputTuple,
    FundsRefundedEvent.OutputTuple,
    FundsRefundedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FundsLocked(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;
    FundsLocked: TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;

    "FundsRefunded(bytes32,address,uint256,uint256)": TypedContractEvent<
      FundsRefundedEvent.InputTuple,
      FundsRefundedEvent.OutputTuple,
      FundsRefundedEvent.OutputObject
    >;
    FundsRefunded: TypedContractEvent<
      FundsRefundedEvent.InputTuple,
      FundsRefundedEvent.OutputTuple,
      FundsRefundedEvent.OutputObject
    >;

    "FundsReleased(bytes32,address,uint256,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
