/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockUSDC } from "./MockUSDC";
export * as factories from "./factories";
export { MockUSDC__factory } from "./factories/MockUSDC__factory";
