/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace JobRegistry {
  export type JobStruct = {
    id: BytesLike;
    buyer: AddressLike;
    provider: AddressLike;
    amount: BigNumberish;
    status: BigNumberish;
    tracked: boolean;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
    reasoningHash: string;
  };

  export type JobStructOutput = [
    id: string,
    buyer: string,
    provider: string,
    amount: bigint,
    status: bigint,
    tracked: boolean,
    createdAt: bigint,
    completedAt: bigint,
    reasoningHash: string
  ] & {
    id: string;
    buyer: string;
    provider: string;
    amount: bigint;
    status: bigint;
    tracked: boolean;
    createdAt: bigint;
    completedAt: bigint;
    reasoningHash: string;
  };
}

export interface JobRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_JOB_DURATION"
      | "acceptJob"
      | "buyerJobs"
      | "completeJob"
      | "createJob"
      | "failJob"
      | "getBuyerJobs"
      | "getJob"
      | "getProviderJobs"
      | "isJobFinalized"
      | "jobList"
      | "jobs"
      | "owner"
      | "providerJobs"
      | "renounceOwnership"
      | "settleJob"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JobAccepted"
      | "JobCompleted"
      | "JobCreated"
      | "JobFailed"
      | "JobSettled"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_JOB_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptJob",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyerJobs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeJob",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [AddressLike, BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "failJob",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyerJobs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getJob", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getProviderJobs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isJobFinalized",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jobList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "providerJobs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settleJob",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_JOB_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "acceptJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyerJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "failJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBuyerJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProviderJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isJobFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "providerJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settleJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace JobAcceptedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    provider: AddressLike,
    acceptedAt: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    provider: string,
    acceptedAt: bigint
  ];
  export interface OutputObject {
    jobId: string;
    provider: string;
    acceptedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [jobId: BytesLike, completedAt: BigNumberish];
  export type OutputTuple = [jobId: string, completedAt: bigint];
  export interface OutputObject {
    jobId: string;
    completedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    buyer: AddressLike,
    provider: AddressLike,
    amount: BigNumberish,
    tracked: boolean,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    buyer: string,
    provider: string,
    amount: bigint,
    tracked: boolean,
    createdAt: bigint
  ];
  export interface OutputObject {
    jobId: string;
    buyer: string;
    provider: string;
    amount: bigint;
    tracked: boolean;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobFailedEvent {
  export type InputTuple = [jobId: BytesLike, reason: string];
  export type OutputTuple = [jobId: string, reason: string];
  export interface OutputObject {
    jobId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobSettledEvent {
  export type InputTuple = [jobId: BytesLike, settledAt: BigNumberish];
  export type OutputTuple = [jobId: string, settledAt: bigint];
  export interface OutputObject {
    jobId: string;
    settledAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface JobRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): JobRegistry;
  waitForDeployment(): Promise<this>;

  interface: JobRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_JOB_DURATION: TypedContractMethod<[], [bigint], "view">;

  acceptJob: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  buyerJobs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  completeJob: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  createJob: TypedContractMethod<
    [
      provider: AddressLike,
      amount: BigNumberish,
      tracked: boolean,
      reasoningHash: string
    ],
    [string],
    "nonpayable"
  >;

  failJob: TypedContractMethod<
    [jobId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getBuyerJobs: TypedContractMethod<[buyer: AddressLike], [string[]], "view">;

  getJob: TypedContractMethod<
    [jobId: BytesLike],
    [JobRegistry.JobStructOutput],
    "view"
  >;

  getProviderJobs: TypedContractMethod<
    [provider: AddressLike],
    [string[]],
    "view"
  >;

  isJobFinalized: TypedContractMethod<[jobId: BytesLike], [boolean], "view">;

  jobList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  jobs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string
      ] & {
        id: string;
        buyer: string;
        provider: string;
        amount: bigint;
        status: bigint;
        tracked: boolean;
        createdAt: bigint;
        completedAt: bigint;
        reasoningHash: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  providerJobs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settleJob: TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_JOB_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptJob"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buyerJobs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "completeJob"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      provider: AddressLike,
      amount: BigNumberish,
      tracked: boolean,
      reasoningHash: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "failJob"
  ): TypedContractMethod<
    [jobId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBuyerJobs"
  ): TypedContractMethod<[buyer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [JobRegistry.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProviderJobs"
  ): TypedContractMethod<[provider: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isJobFinalized"
  ): TypedContractMethod<[jobId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "jobList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string
      ] & {
        id: string;
        buyer: string;
        provider: string;
        amount: bigint;
        status: bigint;
        tracked: boolean;
        createdAt: bigint;
        completedAt: bigint;
        reasoningHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "providerJobs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleJob"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "JobAccepted"
  ): TypedContractEvent<
    JobAcceptedEvent.InputTuple,
    JobAcceptedEvent.OutputTuple,
    JobAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobFailed"
  ): TypedContractEvent<
    JobFailedEvent.InputTuple,
    JobFailedEvent.OutputTuple,
    JobFailedEvent.OutputObject
  >;
  getEvent(
    key: "JobSettled"
  ): TypedContractEvent<
    JobSettledEvent.InputTuple,
    JobSettledEvent.OutputTuple,
    JobSettledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "JobAccepted(bytes32,address,uint256)": TypedContractEvent<
      JobAcceptedEvent.InputTuple,
      JobAcceptedEvent.OutputTuple,
      JobAcceptedEvent.OutputObject
    >;
    JobAccepted: TypedContractEvent<
      JobAcceptedEvent.InputTuple,
      JobAcceptedEvent.OutputTuple,
      JobAcceptedEvent.OutputObject
    >;

    "JobCompleted(bytes32,uint256)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobCreated(bytes32,address,address,uint256,bool,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobFailed(bytes32,string)": TypedContractEvent<
      JobFailedEvent.InputTuple,
      JobFailedEvent.OutputTuple,
      JobFailedEvent.OutputObject
    >;
    JobFailed: TypedContractEvent<
      JobFailedEvent.InputTuple,
      JobFailedEvent.OutputTuple,
      JobFailedEvent.OutputObject
    >;

    "JobSettled(bytes32,uint256)": TypedContractEvent<
      JobSettledEvent.InputTuple,
      JobSettledEvent.OutputTuple,
      JobSettledEvent.OutputObject
    >;
    JobSettled: TypedContractEvent<
      JobSettledEvent.InputTuple,
      JobSettledEvent.OutputTuple,
      JobSettledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
