/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ProviderRegistry {
  export type ProviderStruct = {
    owner: AddressLike;
    metadataURI: string;
    isActive: boolean;
    registeredAt: BigNumberish;
    hourlyRate: BigNumberish;
  };

  export type ProviderStructOutput = [
    owner: string,
    metadataURI: string,
    isActive: boolean,
    registeredAt: bigint,
    hourlyRate: bigint
  ] & {
    owner: string;
    metadataURI: string;
    isActive: boolean;
    registeredAt: bigint;
    hourlyRate: bigint;
  };
}

export interface ProviderRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getProvider"
      | "getProviderCount"
      | "getProviders"
      | "isActiveProvider"
      | "owner"
      | "providerList"
      | "providers"
      | "registerProvider"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateProvider"
      | "updateProviderStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProviderRegistered"
      | "ProviderStatusChanged"
      | "ProviderUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProviders",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "providerList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "providers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProvider",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProvider",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProviderStatus",
    values: [boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "getProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "providerList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "providers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProviderStatus",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderRegisteredEvent {
  export type InputTuple = [
    owner: AddressLike,
    metadataURI: string,
    hourlyRate: BigNumberish,
    registeredAt: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    metadataURI: string,
    hourlyRate: bigint,
    registeredAt: bigint
  ];
  export interface OutputObject {
    owner: string;
    metadataURI: string;
    hourlyRate: bigint;
    registeredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderStatusChangedEvent {
  export type InputTuple = [owner: AddressLike, isActive: boolean];
  export type OutputTuple = [owner: string, isActive: boolean];
  export interface OutputObject {
    owner: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderUpdatedEvent {
  export type InputTuple = [
    owner: AddressLike,
    metadataURI: string,
    isActive: boolean,
    hourlyRate: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    metadataURI: string,
    isActive: boolean,
    hourlyRate: bigint
  ];
  export interface OutputObject {
    owner: string;
    metadataURI: string;
    isActive: boolean;
    hourlyRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProviderRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProviderRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProviderRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProvider: TypedContractMethod<
    [owner: AddressLike],
    [ProviderRegistry.ProviderStructOutput],
    "view"
  >;

  getProviderCount: TypedContractMethod<[], [bigint], "view">;

  getProviders: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  isActiveProvider: TypedContractMethod<
    [owner: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  providerList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  providers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint, bigint] & {
        owner: string;
        metadataURI: string;
        isActive: boolean;
        registeredAt: bigint;
        hourlyRate: bigint;
      }
    ],
    "view"
  >;

  registerProvider: TypedContractMethod<
    [metadataURI: string, hourlyRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateProvider: TypedContractMethod<
    [metadataURI: string, hourlyRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateProviderStatus: TypedContractMethod<
    [isActive: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProvider"
  ): TypedContractMethod<
    [owner: AddressLike],
    [ProviderRegistry.ProviderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProviderCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProviders"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActiveProvider"
  ): TypedContractMethod<[owner: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "providerList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "providers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint, bigint] & {
        owner: string;
        metadataURI: string;
        isActive: boolean;
        registeredAt: bigint;
        hourlyRate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProvider"
  ): TypedContractMethod<
    [metadataURI: string, hourlyRate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProvider"
  ): TypedContractMethod<
    [metadataURI: string, hourlyRate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProviderStatus"
  ): TypedContractMethod<[isActive: boolean], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderRegistered"
  ): TypedContractEvent<
    ProviderRegisteredEvent.InputTuple,
    ProviderRegisteredEvent.OutputTuple,
    ProviderRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderStatusChanged"
  ): TypedContractEvent<
    ProviderStatusChangedEvent.InputTuple,
    ProviderStatusChangedEvent.OutputTuple,
    ProviderStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderUpdated"
  ): TypedContractEvent<
    ProviderUpdatedEvent.InputTuple,
    ProviderUpdatedEvent.OutputTuple,
    ProviderUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProviderRegistered(address,string,uint256,uint256)": TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;
    ProviderRegistered: TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;

    "ProviderStatusChanged(address,bool)": TypedContractEvent<
      ProviderStatusChangedEvent.InputTuple,
      ProviderStatusChangedEvent.OutputTuple,
      ProviderStatusChangedEvent.OutputObject
    >;
    ProviderStatusChanged: TypedContractEvent<
      ProviderStatusChangedEvent.InputTuple,
      ProviderStatusChangedEvent.OutputTuple,
      ProviderStatusChangedEvent.OutputObject
    >;

    "ProviderUpdated(address,string,bool,uint256)": TypedContractEvent<
      ProviderUpdatedEvent.InputTuple,
      ProviderUpdatedEvent.OutputTuple,
      ProviderUpdatedEvent.OutputObject
    >;
    ProviderUpdated: TypedContractEvent<
      ProviderUpdatedEvent.InputTuple,
      ProviderUpdatedEvent.OutputTuple,
      ProviderUpdatedEvent.OutputObject
    >;
  };
}
